# Generated by Django 4.0.3 on 2022-03-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_lesson_slug_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='id',
            field=models.CharField(default='slug', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='id',
            field=models.CharField(default='slug', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='start'),
        ),
    ]
